services:
  api:
    build: ./
    command: sh -c "npm run ${SCRIPT:-start} && npm run codegen"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    #environment:
      #- NODE_ENV=test
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: 'curl --fail --request POST --header ''content-type: application/json'' --url ''http://localhost:8000/graphql'' --data ''{"query":"query { __typename }"}'' || exit 1'
      # test: ["CMD", "curl", "--fail", "http://localhost:8000/graphql"]
      interval: 5s
      timeout: 5s
      retries: 10

  client:
    build: ../client
    volumes:
      - ../client:/app
      - /app/node_modules
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - app-network
    depends_on:
      api:
        condition: service_healthy
    # environment:
    #   - NODE_ENV=development

networks:
  app-network:
    driver: bridge